name: CI

on:
  push:
    branches:
      - master  # 修改为你的主分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # 添加 distribution 参数

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn -B test --file pom.xml

    - name: Deploy to production
    if: github.ref == 'refs/heads/main'  # 可选，只有在主分支推送时才部署
      run: |
        # 在这里添加部署到生产环境的命令，例如使用FTP、SSH或者其他部署工具
        # 示例：scp target/*.jar user@example.com:/path/to/deploy
      
